import type { DB } from './types';
import { DEFAULT_TAGS } from './constants';

const d = (offset: number) => {
  const x = new Date();
  x.setDate(x.getDate() + offset);
  return x.toISOString().slice(0, 10);
};
const dt = (offset: number, h = 10, m = 0) => {
  const x = new Date();
  x.setDate(x.getDate() + offset);
  x.setHours(h, m, 0, 0);
  return x.toISOString();
};

export function seedDB(): DB {
  const apps: DB['apps'] = [
    {
      id: 'app-1',
      company: 'Tokopedia',
      position: 'Frontend Engineer',
      department: 'Product Engineering',
      location: 'Jakarta Selatan',
      workType: 'Hybrid',
      jobType: 'Full Time',
      salaryMin: 12000000,
      salaryMax: 18000000,
      source: 'LinkedIn',
      url: 'https://www.linkedin.com/jobs',
      appliedDate: d(-21),
      deadline: d(3),
      recruiterName: 'Dinda Prameswari',
      recruiterEmail: 'dinda.p@example.com',
      recruiterPhone: '+62 812-3456-7890',
      notes: 'Recruiter minta portfolio versi terbaru dan link GitHub.',
      status: 'user_interview',
      tags: ['Dream Company', 'High Priority'],
      documentIds: ['doc-1', 'doc-4'],
      archived: false,
      favorite: true,
      history: [
        { status: 'applied', at: dt(-21, 9) },
        { status: 'screening', at: dt(-17, 14) },
        { status: 'hr_interview', at: dt(-12, 10) },
        { status: 'user_interview', at: dt(-4, 13) },
      ],
      createdAt: dt(-21, 9),
      updatedAt: dt(-4, 13),
    },
    {
      id: 'app-2',
      company: 'Gojek',
      position: 'Product Designer',
      department: 'Design',
      location: 'Jakarta Pusat',
      workType: 'Remote',
      jobType: 'Full Time',
      salaryMin: 14000000,
      salaryMax: 20000000,
      source: 'Referral',
      url: 'https://www.gojek.com/careers',
      appliedDate: d(-30),
      deadline: '',
      recruiterName: 'Bagas Nugroho',
      recruiterEmail: 'bagas@example.com',
      recruiterPhone: '+62 813-2211-9080',
      notes: 'Direferensikan oleh teman kampus. Fokus ke design system.',
      status: 'offer',
      tags: ['Dream Company', 'Remote', 'Referral'],
      documentIds: ['doc-2'],
      archived: false,
      favorite: true,
      history: [
        { status: 'applied', at: dt(-30, 8) },
        { status: 'screening', at: dt(-26, 11) },
        { status: 'hr_interview', at: dt(-20, 15) },
        { status: 'technical_test', at: dt(-14, 9) },
        { status: 'offer', at: dt(-2, 16) },
      ],
      createdAt: dt(-30, 8),
      updatedAt: dt(-2, 16),
    },
    {
      id: 'app-3',
      company: 'Bank Mandiri',
      position: 'IT Business Analyst',
      department: 'Digital Banking',
      location: 'Jakarta Selatan',
      workType: 'WFO',
      jobType: 'Full Time',
      salaryMin: 9000000,
      salaryMax: 13000000,
      source: 'Jobstreet',
      url: 'https://www.jobstreet.co.id',
      appliedDate: d(-40),
      deadline: d(-10),
      recruiterName: 'Rina Kartika',
      recruiterEmail: 'rina.k@example.com',
      recruiterPhone: '',
      notes: 'Proses BUMN cukup panjang, ada tes kesehatan.',
      status: 'technical_test',
      tags: ['BUMN'],
      documentIds: ['doc-1', 'doc-5', 'doc-6'],
      archived: false,
      favorite: false,
      history: [
        { status: 'applied', at: dt(-40, 10) },
        { status: 'screening', at: dt(-33, 10) },
        { status: 'technical_test', at: dt(-8, 9) },
      ],
      createdAt: dt(-40, 10),
      updatedAt: dt(-8, 9),
    },
    {
      id: 'app-4',
      company: 'Ruangguru',
      position: 'Frontend Engineer',
      department: 'Engineering',
      location: 'Jakarta',
      workType: 'Remote',
      jobType: 'Contract',
      salaryMin: 10000000,
      salaryMax: 15000000,
      source: 'Glints',
      url: 'https://glints.com',
      appliedDate: d(-52),
      deadline: '',
      recruiterName: 'Talent Acquisition',
      recruiterEmail: 'ta@example.com',
      recruiterPhone: '',
      notes: 'Tidak ada kabar setelah tes teknikal.',
      status: 'ghosted',
      tags: ['Remote', 'Startup'],
      documentIds: ['doc-1'],
      archived: false,
      favorite: false,
      history: [
        { status: 'applied', at: dt(-52, 9) },
        { status: 'screening', at: dt(-45, 9) },
        { status: 'technical_test', at: dt(-38, 9) },
        { status: 'ghosted', at: dt(-12, 9) },
      ],
      createdAt: dt(-52, 9),
      updatedAt: dt(-12, 9),
    },
    {
      id: 'app-5',
      company: 'Traveloka',
      position: 'Data Analyst',
      department: 'Business Intelligence',
      location: 'Tangerang',
      workType: 'Hybrid',
      jobType: 'Full Time',
      salaryMin: 11000000,
      salaryMax: 16000000,
      source: 'LinkedIn',
      url: 'https://www.traveloka.com/careers',
      appliedDate: d(-18),
      deadline: d(9),
      recruiterName: 'Nadia Salsabila',
      recruiterEmail: 'nadia.s@example.com',
      recruiterPhone: '+62 878-9911-2233',
      notes: 'Butuh portofolio dashboard SQL & Looker.',
      status: 'screening',
      tags: ['High Priority'],
      documentIds: ['doc-1', 'doc-3'],
      archived: false,
      favorite: false,
      history: [
        { status: 'applied', at: dt(-18, 11) },
        { status: 'screening', at: dt(-6, 11) },
      ],
      createdAt: dt(-18, 11),
      updatedAt: dt(-6, 11),
    },
    {
      id: 'app-6',
      company: 'Bukalapak',
      position: 'QA Engineer',
      department: 'Engineering',
      location: 'Jakarta Selatan',
      workType: 'Hybrid',
      jobType: 'Full Time',
      salaryMin: 8000000,
      salaryMax: 12000000,
      source: 'Kalibrr',
      url: 'https://www.kalibrr.id',
      appliedDate: d(-60),
      deadline: '',
      recruiterName: '',
      recruiterEmail: '',
      recruiterPhone: '',
      notes: 'Ditolak setelah HR interview, kurang pengalaman automation.',
      status: 'rejected',
      tags: ['Fresh Graduate'],
      documentIds: ['doc-1'],
      archived: false,
      favorite: false,
      history: [
        { status: 'applied', at: dt(-60, 8) },
        { status: 'screening', at: dt(-55, 8) },
        { status: 'hr_interview', at: dt(-48, 8) },
        { status: 'rejected', at: dt(-42, 8) },
      ],
      createdAt: dt(-60, 8),
      updatedAt: dt(-42, 8),
    },
    {
      id: 'app-7',
      company: 'Xendit',
      position: 'Software Engineer Intern',
      department: 'Payments',
      location: 'Jakarta',
      workType: 'Remote',
      jobType: 'Internship',
      salaryMin: 4000000,
      salaryMax: 6000000,
      source: 'Website Perusahaan',
      url: 'https://www.xendit.co/careers',
      appliedDate: d(-9),
      deadline: d(14),
      recruiterName: 'Kevin Tanuwijaya',
      recruiterEmail: 'kevin.t@example.com',
      recruiterPhone: '+62 851-7788-1122',
      notes: 'Tes koding pakai HackerRank, 90 menit.',
      status: 'applied',
      tags: ['Startup', 'Remote', 'Fresh Graduate'],
      documentIds: ['doc-1', 'doc-2'],
      archived: false,
      favorite: false,
      history: [{ status: 'applied', at: dt(-9, 20) }],
      createdAt: dt(-9, 20),
      updatedAt: dt(-9, 20),
    },
    {
      id: 'app-8',
      company: 'Pertamina',
      position: 'IT Support Officer',
      department: 'Corporate IT',
      location: 'Jakarta Pusat',
      workType: 'WFO',
      jobType: 'Contract',
      salaryMin: 7000000,
      salaryMax: 9000000,
      source: 'Job Fair',
      url: '',
      appliedDate: '',
      deadline: d(20),
      recruiterName: '',
      recruiterEmail: '',
      recruiterPhone: '',
      notes: 'Belum dilamar, menunggu update CV versi ATS.',
      status: 'wishlist',
      tags: ['BUMN'],
      documentIds: [],
      archived: false,
      favorite: false,
      history: [],
      createdAt: dt(-3, 19),
      updatedAt: dt(-3, 19),
    },
    {
      id: 'app-9',
      company: 'Shopee',
      position: 'Frontend Engineer',
      department: 'Engineering',
      location: 'Jakarta Selatan',
      workType: 'WFO',
      jobType: 'Full Time',
      salaryMin: 13000000,
      salaryMax: 19000000,
      source: 'LinkedIn',
      url: 'https://careers.shopee.co.id',
      appliedDate: d(-72),
      deadline: '',
      recruiterName: 'Agnes Wibowo',
      recruiterEmail: 'agnes.w@example.com',
      recruiterPhone: '',
      notes: 'Mengundurkan diri karena menerima proses lain.',
      status: 'withdrawn',
      tags: [],
      documentIds: ['doc-1'],
      archived: true,
      favorite: false,
      history: [
        { status: 'applied', at: dt(-72, 9) },
        { status: 'screening', at: dt(-66, 9) },
        { status: 'withdrawn', at: dt(-58, 9) },
      ],
      createdAt: dt(-72, 9),
      updatedAt: dt(-58, 9),
    },
    {
      id: 'app-10',
      company: 'Telkom Indonesia',
      position: 'Backend Developer',
      department: 'Digital Platform',
      location: 'Bandung',
      workType: 'Hybrid',
      jobType: 'Full Time',
      salaryMin: 10000000,
      salaryMax: 14000000,
      source: 'Website Perusahaan',
      url: 'https://digitalent.telkom.co.id',
      appliedDate: d(-5),
      deadline: d(1),
      recruiterName: 'Hendra Saputra',
      recruiterEmail: 'hendra.s@example.com',
      recruiterPhone: '+62 822-4455-6677',
      notes: 'Wajib melampirkan transkrip dan ijazah.',
      status: 'applied',
      tags: ['BUMN', 'High Priority'],
      documentIds: ['doc-5', 'doc-6'],
      archived: false,
      favorite: false,
      history: [{ status: 'applied', at: dt(-5, 7) }],
      createdAt: dt(-5, 7),
      updatedAt: dt(-5, 7),
    },
    {
      id: 'app-11',
      company: 'Halodoc',
      position: 'Product Manager Associate',
      department: 'Product',
      location: 'Jakarta Selatan',
      workType: 'Hybrid',
      jobType: 'Full Time',
      salaryMin: 12000000,
      salaryMax: 17000000,
      source: 'Glints',
      url: 'https://glints.com',
      appliedDate: d(-2),
      deadline: d(11),
      recruiterName: 'Farah Aulia',
      recruiterEmail: 'farah.a@example.com',
      recruiterPhone: '',
      notes: 'Baru kirim, follow up minggu depan.',
      status: 'applied',
      tags: ['Startup'],
      documentIds: ['doc-1', 'doc-2'],
      archived: false,
      favorite: false,
      history: [{ status: 'applied', at: dt(-2, 21) }],
      createdAt: dt(-2, 21),
      updatedAt: dt(-2, 21),
    },
    {
      id: 'app-12',
      company: 'Sinar Mas Land',
      position: 'UI Designer',
      department: 'Digital Marketing',
      location: 'Tangerang',
      workType: 'WFO',
      jobType: 'Part Time',
      salaryMin: 5000000,
      salaryMax: 7000000,
      source: 'Instagram',
      url: '',
      appliedDate: d(-14),
      deadline: '',
      recruiterName: 'Yoga Pratama',
      recruiterEmail: 'yoga.p@example.com',
      recruiterPhone: '+62 856-1200-3344',
      notes: 'Sudah kirim portofolio, menunggu jadwal interview.',
      status: 'hr_interview',
      tags: ['Fresh Graduate'],
      documentIds: ['doc-3'],
      archived: false,
      favorite: false,
      history: [
        { status: 'applied', at: dt(-14, 10) },
        { status: 'screening', at: dt(-9, 10) },
        { status: 'hr_interview', at: dt(-1, 10) },
      ],
      createdAt: dt(-14, 10),
      updatedAt: dt(-1, 10),
    },
    {
      id: 'app-13',
      company: 'Kredivo',
      position: 'Frontend Engineer',
      department: 'Engineering',
      location: 'Jakarta Selatan',
      workType: 'Remote',
      jobType: 'Full Time',
      salaryMin: 15000000,
      salaryMax: 22000000,
      source: 'Referral',
      url: 'https://www.kredivocorp.com/careers',
      appliedDate: d(-45),
      deadline: '',
      recruiterName: 'Melisa Chandra',
      recruiterEmail: 'melisa.c@example.com',
      recruiterPhone: '+62 811-9090-1234',
      notes: 'Offer diterima sebagai cadangan, masih dipertimbangkan.',
      status: 'accepted',
      tags: ['Remote', 'Referral', 'High Priority'],
      documentIds: ['doc-1', 'doc-4'],
      archived: false,
      favorite: true,
      history: [
        { status: 'applied', at: dt(-45, 9) },
        { status: 'screening', at: dt(-41, 9) },
        { status: 'hr_interview', at: dt(-35, 9) },
        { status: 'technical_test', at: dt(-28, 9) },
        { status: 'user_interview', at: dt(-20, 9) },
        { status: 'offer', at: dt(-11, 9) },
        { status: 'accepted', at: dt(-6, 9) },
      ],
      createdAt: dt(-45, 9),
      updatedAt: dt(-6, 9),
    },
  ];

  const activities: DB['activities'] = [
    { id: 'act-1', appId: 'app-1', type: 'created', title: 'Lamaran dikirim ke Tokopedia', description: 'Melamar posisi Frontend Engineer melalui LinkedIn.', date: dt(-21, 9) },
    { id: 'act-2', appId: 'app-1', type: 'email', title: 'Email HR diterima', description: 'Dinda mengirim undangan screening call.', date: dt(-17, 14) },
    { id: 'act-3', appId: 'app-1', type: 'interview', title: 'HR Interview selesai', description: 'Bahas ekspektasi gaji dan availability.', date: dt(-12, 10) },
    { id: 'act-4', appId: 'app-1', type: 'interview', title: 'User Interview dijadwalkan', description: 'Bersama Engineering Manager, 60 menit via Google Meet.', date: dt(-4, 13) },
    { id: 'act-5', appId: 'app-2', type: 'offer', title: 'Offer diterima dari Gojek', description: 'Total paket 20 juta, mulai bulan depan.', date: dt(-2, 16) },
    { id: 'act-6', appId: 'app-2', type: 'test', title: 'Design challenge selesai', description: 'Mengerjakan redesign flow pemesanan dalam 3 hari.', date: dt(-14, 9) },
    { id: 'act-7', appId: 'app-3', type: 'test', title: 'Technical test Bank Mandiri', description: 'Tes logika dan studi kasus proses bisnis.', date: dt(-8, 9) },
    { id: 'act-8', appId: 'app-4', type: 'followup', title: 'Follow up ke Ruangguru', description: 'Kirim email follow up, belum ada balasan.', date: dt(-24, 9) },
    { id: 'act-9', appId: 'app-5', type: 'email', title: 'Screening call Traveloka', description: 'Membahas pengalaman SQL dan visualisasi data.', date: dt(-6, 11) },
    { id: 'act-10', appId: 'app-7', type: 'created', title: 'Lamaran dikirim ke Xendit', description: 'Program internship 6 bulan.', date: dt(-9, 20) },
    { id: 'act-11', appId: 'app-13', type: 'offer', title: 'Offer Kredivo diterima', description: 'Menandatangani offering letter.', date: dt(-6, 9) },
    { id: 'act-12', appId: 'app-12', type: 'interview', title: 'HR Interview Sinar Mas Land', description: 'Interview santai 30 menit membahas portofolio.', date: dt(-1, 10) },
    { id: 'act-13', appId: null, type: 'note', title: 'Perbarui CV versi ATS', description: 'Menyesuaikan keyword dengan job description terbaru.', date: dt(-7, 20) },
    { id: 'act-14', appId: 'app-10', type: 'document', title: 'Melampirkan ijazah & transkrip', description: 'Unggah berkas ke portal rekrutmen Telkom.', date: dt(-5, 7) },
  ];

  const reminders: DB['reminders'] = [
    { id: 'rem-1', appId: 'app-1', type: 'interview', title: 'User Interview Tokopedia', datetime: dt(1, 13, 30), notes: 'Google Meet bersama Engineering Manager.', done: false },
    { id: 'rem-2', appId: 'app-3', type: 'technical_test', title: 'Technical test Bank Mandiri', datetime: dt(2, 9, 0), notes: 'Durasi 120 menit, online proctored.', done: false },
    { id: 'rem-3', appId: 'app-11', type: 'followup', title: 'Follow up HR Halodoc', datetime: dt(4, 10, 0), notes: 'Kirim email singkat menanyakan progres.', done: false },
    { id: 'rem-4', appId: 'app-10', type: 'deadline', title: 'Deadline lamaran Telkom', datetime: dt(1, 23, 0), notes: 'Pastikan semua berkas lengkap.', done: false },
    { id: 'rem-5', appId: null, type: 'cv_validity', title: 'Perbarui CV utama', datetime: dt(12, 9, 0), notes: 'CV terakhir diperbarui 3 bulan lalu.', done: false },
    { id: 'rem-6', appId: 'app-5', type: 'followup', title: 'Follow up Traveloka', datetime: dt(-2, 10, 0), notes: 'Sudah dikirim lewat email.', done: true },
    { id: 'rem-7', appId: 'app-7', type: 'technical_test', title: 'Coding test Xendit', datetime: dt(6, 19, 0), notes: 'HackerRank, 90 menit.', done: false },
  ];

  const docs: DB['docs'] = [
    { id: 'doc-1', name: 'CV_Utama_v3.pdf', label: 'CV v3', group: 'CV Utama', category: 'cv', language: 'id', version: 'v3', size: 284000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-30, 9), note: 'Versi terbaru dengan pengalaman magang.' },
    { id: 'doc-2', name: 'CV_ATS_English.pdf', label: 'CV ATS – English', group: 'CV Utama', category: 'cv', language: 'en', version: 'v2', size: 198000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-20, 9), note: 'Format ATS friendly, satu kolom.' },
    { id: 'doc-3', name: 'Portfolio_2024.pdf', label: 'Portfolio 2024', group: 'Portfolio', category: 'portfolio', language: '-', version: 'v1', size: 4200000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-40, 9), note: '8 studi kasus produk digital.' },
    { id: 'doc-4', name: 'Cover_Letter_Tokopedia.pdf', label: 'Cover Letter – Tokopedia', group: 'Cover Letter', category: 'cover_letter', language: 'id', version: 'v1', size: 64000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-21, 9), note: 'Disesuaikan dengan nilai perusahaan.' },
    { id: 'doc-5', name: 'Ijazah_S1.pdf', label: 'Ijazah S1', group: 'Akademik', category: 'diploma', language: 'id', version: 'v1', size: 890000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-90, 9), note: '' },
    { id: 'doc-6', name: 'Transkrip_Nilai.pdf', label: 'Transkrip Nilai', group: 'Akademik', category: 'transcript', language: 'id', version: 'v1', size: 760000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-90, 9), note: 'IPK 3.62' },
    { id: 'doc-7', name: 'Sertifikat_AWS_CP.pdf', label: 'AWS Cloud Practitioner', group: 'Sertifikat', category: 'certificate', language: 'en', version: 'v1', size: 320000, mime: 'application/pdf', dataUrl: null, uploadedAt: dt(-60, 9), note: 'Berlaku sampai 2027.' },
  ];

  const notes: DB['notes'] = [
    {
      id: 'note-1',
      appId: 'app-1',
      stage: 'HR Interview',
      date: d(-12),
      qa: [
        { q: 'Ceritakan tentang dirimu.', a: 'Menjelaskan latar belakang sebagai frontend engineer dengan 2 tahun pengalaman di React dan TypeScript.' },
        { q: 'Kenapa tertarik dengan perusahaan ini?', a: 'Karena skala produk dan dampaknya ke jutaan pengguna UMKM Indonesia.' },
        { q: 'Ekspektasi gaji?', a: 'Menyebut range 15–18 juta dengan alasan benchmark pasar.' },
      ],
      feedback: 'HR bilang komunikasi jelas, tapi minta contoh dampak yang lebih terukur.',
      strengths: 'Tenang, runtut, dan paham produk perusahaan.',
      weaknesses: 'Kurang menyebut angka/metrik dari pencapaian sebelumnya.',
      toLearn: 'Siapkan 3 cerita STAR dengan metrik konkret.',
    },
    {
      id: 'note-2',
      appId: 'app-2',
      stage: 'User Interview',
      date: d(-14),
      qa: [
        { q: 'Bagaimana kamu membangun design system?', a: 'Mulai dari audit komponen, token warna, lalu dokumentasi di Figma.' },
        { q: 'Bagaimana menangani konflik dengan engineer?', a: 'Menyamakan tujuan lewat data dan prototipe cepat.' },
      ],
      feedback: 'Interviewer suka pendekatan sistematis dan dokumentasi rapi.',
      strengths: 'Portofolio kuat, penjelasan proses detail.',
      weaknesses: 'Kurang membahas trade-off waktu rilis.',
      toLearn: 'Pelajari prioritisasi RICE dan estimasi effort.',
    },
    {
      id: 'note-3',
      appId: 'app-6',
      stage: 'HR Interview',
      date: d(-48),
      qa: [{ q: 'Pengalaman automation testing?', a: 'Baru sebatas manual testing dan sedikit Cypress.' }],
      feedback: 'Ditolak karena butuh kandidat dengan pengalaman automation lebih dalam.',
      strengths: 'Detail dan teliti saat menjelaskan test case.',
      weaknesses: 'Minim pengalaman framework automation.',
      toLearn: 'Kuasai Playwright dan konsep CI/CD testing.',
    },
  ];

  const bookmarks: DB['bookmarks'] = [
    { id: 'bm-1', company: 'Grab', position: 'Software Engineer', url: 'https://grab.careers', source: 'LinkedIn', deadline: d(12), note: 'Butuh pengalaman Golang, siapkan dulu.', favorite: true, savedAt: dt(-4, 20) },
    { id: 'bm-2', company: 'Sea Labs', position: 'Frontend Engineer', url: 'https://career.sea.com', source: 'Website Perusahaan', deadline: d(25), note: 'Ada tes algoritma, latihan LeetCode dulu.', favorite: false, savedAt: dt(-6, 20) },
    { id: 'bm-3', company: 'BCA', position: 'IT Trainee', url: 'https://karir.bca.co.id', source: 'Job Fair', deadline: d(5), note: 'Program trainee 1 tahun, ikatan dinas.', favorite: false, savedAt: dt(-10, 20) },
  ];

  const wishes: DB['wishes'] = [
    { id: 'wl-1', company: 'Google Indonesia', role: 'Software Engineer', prep: 'preparing', skills: ['Data Structures', 'System Design', 'English Interview'], deadline: d(45), notes: 'Target melamar setelah selesai 150 soal LeetCode.' },
    { id: 'wl-2', company: 'Gojek', role: 'Senior Product Designer', prep: 'ready', skills: ['Design System', 'Prototyping'], deadline: d(10), notes: 'Portofolio sudah siap, tinggal kirim.' },
    { id: 'wl-3', company: 'Pertamina', role: 'Data Engineer', prep: 'research', skills: ['Airflow', 'Spark', 'Tes BUMN'], deadline: d(60), notes: 'Pelajari pola soal rekrutmen bersama BUMN.' },
  ];

  return {
    apps,
    activities,
    reminders,
    docs,
    notes,
    bookmarks,
    wishes,
    tags: DEFAULT_TAGS,
    settings: {
      theme: 'light',
      language: 'id',
      timezone: 'Asia/Jakarta',
      weeklyTarget: 5,
      monthlyTarget: 20,
      emailNotif: true,
      dailyReminder: true,
      notifyEmail: '',
      cvValidDays: 90,
    },
    user: null,
  };
}
